// <auto-generated />
namespace Reyx.Web.Workshop.Knockout.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostAddTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostAddTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201307290321390_PostAddTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
